language: python
matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
install:
  - sudo apt install libvirt-dev
  - pip install --upgrade pip
  - pip install --upgrade mock
  - pip install --upgrade pytest
  - pip install --upgrade setuptools
  - pip install -I libvirt-python==4.0.0
  - pip install .
script:
  - python -m pytest -v
branches:
  only:
    - master
