dist: xenial
language: python
virtualenv:
  system_site_packages: true
matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
install:
  - sudo apt update
  - sudo apt install python-ipaddress python-libvirt python3-libvirt
  - pip install --upgrade pip
  - pip install --upgrade mock
  - pip install --upgrade pytest
  - pip install --upgrade setuptools
script:
  - python -m pytest -v
branches:
  only:
    - master
